### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by foocker** [parap1uie-s/Keras-RFCN#4]
Could you describe in detail  about the data parameters and file organization?I want train this model for my data, but the data generator is always meet problems.Thanks very much.

**Comment by foocker** [comment]
especial the keywords:source

**Comment by parap1uie-s** [comment]
So the most important is **load_image(image_id)** and **load_bbox(image_id)**

Our model just cares about "what image data is provided, and what boxes data is provided"

Any other functions have a common effect: provide the necessary information for these two functions.

So, in **initDB()**, you define a dataset which contains all your image file path.

Note we have lazy load and don't load the image data(numpy array) at this point , we just define these things:

How many classes of boxes in your data? And what is the relationship between class_id(from 1) to class_name?

How many images do you have? You need to assign each image **path** to a **image_id**.

What are the image size of each image? You need to provide image's width and height, two int number.

As for the **bboxes** , that is not necessary in **initDB()**, you can provide that in **load_bbox()** according to the **image_id** parameter of the function. 

But providing the boxes in initDB like the way in Fashion_Train.py, you could easily get the boxes data without the needs of read the Disk, which makes the generator runs faster.

The **source** keyword is not most important, you can rename it to anything you want. But remember to rename the Attributes: YourDataConfig/NAME like line31@Fashion_Train.py too.

**Comment by foocker** [comment]
Thanks very much for your reply .today, i have  read your code carefully  and now its running normally.
source, i guess:different database have different classes, but there can be overlap from them.
i mean , source={'coco':[0, 1, 2, 3], 'voc04':[0, 1, 5, 9],'voc07':[0, 1, 2, 4, 5, 6]}

**Comment by parap1uie-s** [comment]
Well, in fact, the **source** parameter is not as useful as you think, and taking it with a **string** is fine.

And the map of {classid -> class_name}, you shouldn't write it in **source**.

Like this:
```
for class_name, class_id in class_mapping.items():
       self.add_class("Fashion", class_id , class_name)
```

Then you need to return the **coordinates** and **class_id** of each box in _load_bbox(self, image_id)_

And the issue will be closed.
